# Generated by Django 5.2.4 on 2025-07-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='description',
            new_name='consultation_topic',
        ),
    ]
